mongo:
  uri: "mongodb+srv://ciroandressanchezbuitrago:l7BMBJRvdGPoiq96@personal.p0j5b.mongodb.net/?retryWrites=true&w=majority&appName=personalop "
  database: "Factions"

# In seconds
db-saving-rate: 30000

rank-provider: "LuckPerms"

# Recommended: 3000
rtp-radius: 3000
chat:
  format: "{team} {rank} {name} <dark_gray>»</dark_gray> <gray>{message}</gray>"
  staff-format: "<light_purple>(Staff Chat) {name}: </light_purple> <yellow>{message}</yellow>"
  admin-format: "<red>(Admin Chat) {name}: </red> <yellow>{message}</yellow>"


worlds:
  main:
    world-name: "main"
    display-name: "<green>Spawn World</green>"
  wilderness:
    world-name: "wilderness"
    display-name: "<yellow>Wilderness World</yellow>"
  nether:
    world-name: "nether"
    display-name: "<red>Nether World</red>"
  end:
    world-name: "end"
    display-name: "<purple>End World</purple>"
  events:
    world-name: "events"
    display-name: "<blue>Events</blue>"

spawn:
  # Name of the spawn
  name: "<green>Spawn</green>"
  # Time it takes to teleport spawn
  time-to-tp: 3
  # Radius that player can move around without cancelling spawn
  radius: 5

team-limit: 20


koth:
  display-name: "<aqua>{name}</aqua> <gold>KoTH</gold>"
  timer-format: "<aqua>{name}</aqua>"
  points: 20


citadel:
  display-name: "<dark_purple>Citadel</dark_purple>"
  duration: 10m
conquest:
  display-name: "<gold>Conquest</gold>"
  duration: 5m
  points: 500
  death: 40

team:
  size: 20

points:
  death: 0
  kill: 1
